"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# Read from the environment so the same code runs in production, but fall back to a
# baked-in value so the project boots with zero setup. The fallback is safe *only*
# because it is never used when DJANGO_SECRET_KEY is set.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-r50tf=#zi675n+o)^$l#q-$t-j&%02#^rj-3ta_ie7qc)0(7m0',
)

# Default to True for local development; production sets DJANGO_DEBUG=0.
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # --- Third party ---
    'rest_framework',      # DRF: serializers, viewsets, routers, browsable API
    'corsheaders',         # Cross-origin support for the standalone-frontend case
    'django_filters',      # Declarative ?field=value filtering on list endpoints
    # --- Local ---
    'api',                 # All application code lives here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CorsMiddleware must sit ABOVE CommonMiddleware. CommonMiddleware can issue
    # redirects (e.g. APPEND_SLASH), and a redirect that has not yet passed through
    # CorsMiddleware carries no CORS headers -- the browser then reports an opaque
    # failure that looks nothing like the redirect that actually caused it.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# SQLite is used here because it needs no running service and no credentials, which
# keeps the project cloneable and runnable in one command. Nothing in the application
# depends on SQLite specifically -- the ORM abstracts it, so moving to Postgres
# (Supabase in production) is a change to this dict alone:
#
#     DATABASES = {'default': dj_database_url.parse(os.environ['DATABASE_URL'])}
#
# The one caveat worth knowing: Postgres-only features (JSONB operators, full-text
# search, ArrayField) are unavailable while on SQLite.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Default primary key type for models that don't declare one.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------------------------------------
# Django REST Framework
# --------------------------------------------------------------------------------
REST_FRAMEWORK = {
    # Paginate every list endpoint by default. Opting in per-view is easy to forget,
    # and an unpaginated list that works on 20 rows will fall over on 20,000.
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # Makes `filterset_fields = [...]` work on any ViewSet without further wiring.
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    # The browsable API is a genuinely useful manual-testing tool in development, but
    # it renders templates and leaks endpoint structure, so it is excluded from
    # production responses.
    'DEFAULT_RENDERER_CLASSES': (
        [
            'rest_framework.renderers.JSONRenderer',
            'rest_framework.renderers.BrowsableAPIRenderer',
        ]
        if DEBUG
        else ['rest_framework.renderers.JSONRenderer']
    ),

    # Return timestamps as ISO-8601, which JavaScript's Date can parse directly.
    'DATETIME_FORMAT': 'iso-8601',
}


# --------------------------------------------------------------------------------
# CORS
# --------------------------------------------------------------------------------
# In development the SvelteKit dev server proxies /api -> :8000 (see
# frontend/vite.config.ts), so the browser sees same-origin requests and CORS never
# comes into play. This block is the fallback for when the frontend is served
# separately -- a deployed static build, or running Vite without the proxy.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Required only if the frontend ever authenticates with Django session cookies
# rather than a token in the Authorization header.
CORS_ALLOW_CREDENTIALS = True

# Django 4+ verifies the Origin header on unsafe (POST/PUT/PATCH/DELETE) requests.
# Without this the proxied frontend gets a 403 on every write.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
